// Code generated by github.com/vektah/gqlgen, DO NOT EDIT.

package gqlgen

type NewUser struct {
	Name string `json:"name"`
}
type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
